### ISSUE TITLE
TypeError: float() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by inetkenya** [RemiTheWarrior/epidemic-simulator#15]
The below error started today. Am not sure what this is. Am running this from my local PC

daniel@Daniels-MacBook-Pro:~/Downloads/epidemic-simulator-master 2$ python fit_any_country.py --noplot Malaysia
Traceback (most recent call last):
  File "fit_any_country.py", line 98, in <module>
    time, time_number_days, cases_ref, deaths_ref = get_data(country)
  File "/Users/daniel/Downloads/epidemic-simulator-master 2/data.py", line 34, in get_data
    cases.append(float(entry["confirmed"]) - float(entry["recovered"]) - float(entry["deaths"]))
TypeError: float() argument must be a string or a number, not 'NoneType'

**Comment by RemDelaporteMathurin** [comment]
Hi, it's related to [this issue](https://github.com/pomber/covid19/issues/64).
Since yesterday, the source file has no "recovered" entry (or more precisely has a None entry). I'm working on a fix

**Comment by RemDelaporteMathurin** [comment]
One way to do it is to use the last know value but this will mess with the calculations. If you have any suggestions, I'm all ears

**Comment by RemDelaporteMathurin** [comment]
@inetkenya It should be fixed now. There are still "null" data for 2020-3-25 but I worked a fix out. Let me know if it's work for you

**Comment by inetkenya** [comment]
@RemiTheWarrior ..It works well bro. How can I get this to give me the most current data? Currently, for Malaysia, the numbers have hit over 2300 but the plot still shows under 2000.

I will close this within today, thanks buddy. Do share in your RD how to use the other script "fit_every_country.py"

**Comment by RemDelaporteMathurin** [comment]
@inetkenya Great!

The data is taken from [pomber/covid19](https://github.com/pomber/covid19) and is updated 3 times a day. It will certainly be updated today or tomorrow 😄

**Comment by RemDelaporteMathurin** [comment]
Concerning the "fit_every_country.py", the script just writes everything to .json files. I use that for updating the [web app](https://epidemic-simulator.now.sh/#/).

But if you're interested, simply run 
```
$ python3 fit_every_country.py
```
